Copyright 2021-2023 @ Shenzhen Bay Laboratory & Peking University & Huawei Technologies Co., Ltd

This code is a part of Cybertron package.

The Cybertron is open-source software based on the AI-framework:
MindSpore (https://www.mindspore.cn/)

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.

You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.

See the License for the specific language governing permissions and
limitations under the License.

Cybertron tutorial 00: The preprocessing of dataset

The NPZ file can be download from:
dataset_qm9.npz: http://gofile.me/6Utp7/tJ5hoDIAo
ethanol_dft.npz: http://gofile.me/6Utp7/hbQBofAFM

In [1]:
import numpy as np
from cybertron.dataset import DatasetProcessor

In [2]:
qm9_file = 'dataset_qm9.npz'
qm9_data = np.load(qm9_file)
for k, v in qm9_data.items():
    print(k, v.shape)

atom_ref (10, 6)
valid_idx (100,)
uncharacterized (3054,)
excluded (11,)
Nos (133885, 1)
Natom (133885, 1)
SMILES (133885, 2)
InChI (133885, 2)
Z (133885, 29)
R (133885, 29, 3)
Q (133885, 29)
properties (133885, 15)
frequencies (133885, 150)


In [3]:
atom_ref = qm9_data['atom_ref']
ref = np.zeros((atom_ref.shape[0], 6))
atom_ref = np.concatenate((ref, atom_ref), axis=-1)

ds_qm9 = DatasetProcessor(
    name='qm9',
    atom_types=qm9_data['Z'],
    position=qm9_data['R'],
    label=qm9_data['properties'][:, 3:],
    length_unit='A',
    energy_unit='Ha',
    type_ref=atom_ref,
)

Number of atoms: 29
Number of data: 133885
Dimension of space: 3
Total number of effective atoms: 2407753
Shape of atom types (Z): (133885, 29)
Shape of position (R): (133885, 29, 3)
Shape of label (E): (133885, 12)
Reference value for atom types:
   Type     Label0    Label1    Label2    Label3    Label4    Label5    Label6    Label7    Label8    Label9   Label10   Label11
   0:        0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00
   1:        0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00 -5.00e-01 -4.99e-01 -4.98e-01 -5.11e-01  2.98e+00
   2:        0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00
   3:        0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00
   4:        0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.

In [4]:
exc_idx = np.concatenate(
    (qm9_data['excluded'], qm9_data['uncharacterized']), -1) - 1
ds_qm9.exclude_data(exc_idx)

Remove 3062 samples from 130823 dataset.
---------------------------------------------------------------------------------------------------------
Label analysis according to graph:
   ID              Mean             STD             Min             Max          Median           Range
    0:     2.672827e+00    1.503183e+00    0.000000e+00    2.955640e+01    2.475200e+00    2.955640e+01
    1:     7.528103e+01    8.173763e+00    6.310000e+00    1.966200e+02    7.560000e+01    1.903100e+02
    2:    -2.402090e-01    2.196555e-02   -4.286000e-01   -1.017000e-01   -2.411000e-01    3.269000e-01
    3:     1.184083e-02    4.684326e-02   -1.750000e-01    1.935000e-01    1.260000e-02    3.685000e-01
    4:     2.520497e-01    4.718871e-02    2.460000e-02    6.221000e-01    2.502000e-01    5.975000e-01
    5:     1.189402e+03    2.804632e+02    1.900020e+01    3.374753e+03    1.147221e+03    3.355753e+03
    6:     1.490930e-01    3.313445e-02    1.595100e-02    2.739440e-01    1.486310e-01   

array([     0,      1,      2, ..., 133882, 133883, 133884], dtype=int32)

In [5]:
ds_qm9.convert_units('nm', 'kj/mol', [2, 3, 4, 6, 7, 8, 9, 10])

Change the length unit from "Angstrom" to "nm"
Change the energy unit from "Hartree" to "kJ mol-1"
---------------------------------------------------------------------------------------------------------
Label analysis according to graph:
   ID              Mean             STD             Min             Max          Median           Range
    0:     2.672827e+00    1.503183e+00    0.000000e+00    2.955640e+01    2.475200e+00    2.955640e+01
    1:     7.528103e+01    8.173763e+00    6.310000e+00    1.966200e+02    7.560000e+01    1.903100e+02
    2:    -6.306687e+02    5.767056e+01   -1.125289e+03   -2.670134e+02   -6.330081e+02    8.582760e+02
    3:     3.108809e+01    1.229870e+02   -4.594625e+02    5.080343e+02    3.308130e+01    9.674968e+02
    4:     6.617564e+02    1.238940e+02    6.458730e+01    1.633324e+03    6.569002e+02    1.568736e+03
    5:     1.189402e+03    2.804632e+02    1.900020e+01    3.374753e+03    1.147221e+03    3.355753e+03
    6:     3.914438e+02    8.699

In [6]:
ds_qm9.shuffle_dataset()

array([ 31571,  24330,  24912, ..., 129313, 112473,  14473], dtype=int32)

In [7]:
mode = ['graph', 'graph', 'graph', 'graph', 'graph', 'graph',
        'graph', 'atomwise', 'atomwise', 'atomwise', 'atomwise', 'graph']
ds_qm9.save_dataset('dataset_qm9', 1024, 128, 1024,
                    norm_train=True, norm_valid=True, norm_test=True, mode=mode)

   ID.            Scale           Shift        Mode
    0.     1.503183e+00    2.672827e+00       graph
    1.     8.173763e+00    7.528103e+01       graph
    2.     5.767056e+01   -6.306687e+02       graph
    3.     1.229870e+02    3.108809e+01       graph
    4.     1.238940e+02    6.617564e+02       graph
    5.     2.804632e+02    1.189402e+03       graph
    6.     8.699451e+01    3.914438e+02       graph
    7.     1.824854e+01   -4.094204e+02    atomwise
    8.     1.818079e+01   -4.118893e+02    atomwise
    9.     1.816252e+01   -4.142276e+02    atomwise
   10.     1.807273e+01   -3.811549e+02    atomwise
   11.     6.082039e+00   -2.213512e+01       graph
---------------------------------------------------------------------------------------------------------
Number of Training, Validation and Test dataset: 1024, 128, 1024.
---------------------------------------------------------------------------------------------------------
Dataset file:
   Training dataset    (normaliz

({'name': 'qm9',
  'num_atoms': 29,
  'num_dataset': 1024,
  'data_index': array([32571, 24866, 25551, ..., 33699, 15085,  8592], dtype=int32),
  'normed_dataset': False,
  'length_unit': 'nm',
  'energy_unit': 'kj/mol',
  'type_ref': array([[ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
           0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
           0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
         [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
           0.0000000e+00,  0.0000000e+00,  0.0000000e+00, -1.3134669e+03,
          -1.3097491e+03, -1.3072681e+03, -1.3414390e+03,  2.9809999e+00],
         [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
           0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
           0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
         [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
           0.0000000e+00

In [8]:
ds_qm9.save_dataset('dataset_qm9', 1024, 128, 1024, norm_train=False,
                    norm_valid=False, norm_test=False, mode=mode)

   ID.            Scale           Shift        Mode
    0.     1.503183e+00    2.672827e+00       graph
    1.     8.173763e+00    7.528103e+01       graph
    2.     5.767056e+01   -6.306687e+02       graph
    3.     1.229870e+02    3.108809e+01       graph
    4.     1.238940e+02    6.617564e+02       graph
    5.     2.804632e+02    1.189402e+03       graph
    6.     8.699451e+01    3.914438e+02       graph
    7.     1.824854e+01   -4.094204e+02    atomwise
    8.     1.818079e+01   -4.118893e+02    atomwise
    9.     1.816252e+01   -4.142276e+02    atomwise
   10.     1.807273e+01   -3.811549e+02    atomwise
   11.     6.082039e+00   -2.213512e+01       graph
---------------------------------------------------------------------------------------------------------
Number of Training, Validation and Test dataset: 1024, 128, 1024.
---------------------------------------------------------------------------------------------------------
Dataset file:
   Training dataset        (orig

({'name': 'qm9',
  'num_atoms': 29,
  'num_dataset': 1024,
  'data_index': array([32571, 24866, 25551, ..., 33699, 15085,  8592], dtype=int32),
  'normed_dataset': False,
  'length_unit': 'nm',
  'energy_unit': 'kj/mol',
  'type_ref': array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
           0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
           0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
           0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
         [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
           0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
           0.00000000e+00, -1.31346686e+03, -1.30974915e+03,
          -1.30726806e+03, -1.34143894e+03,  2.98100000e+00],
         [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
           0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
           0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
           0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
         [ 0.00000000e+00,  0.00

In [9]:
md17_data = np.load('ethanol_dft.npz')
for k, v in md17_data.items():
    print(k, v.shape)

E (555092, 1)
name ()
F (555092, 9, 3)
theory ()
R (555092, 9, 3)
z (9,)
type ()
md5 ()


In [10]:
ds_md17 = DatasetProcessor(
    name='md17',
    atom_types=md17_data['z'],
    position=md17_data['R'],
    label=md17_data['E'],
    force=md17_data['F'],
    length_unit='A',
    energy_unit='kcal/mol',
)

Number of atoms: 9
Number of data: 555092
Dimension of space: 3
Total number of effective atoms: 4995828
Shape of atom types (Z): (1, 9)
Shape of position (R): (555092, 9, 3)
Shape of label (E): (555092, 1)
Shape of force (F): (555092, 9, 3)
Length unit: Angstrom
Energy unit: kcal mol-1
---------------------------------------------------------------------------------------------------------
Label analysis according to graph:
               Mean             STD             Min             Max          Median           Range
      -9.719593e+04    4.192011e+00   -9.720841e+04   -9.717179e+04   -9.719637e+04    3.661111e+01
---------------------------------------------------------------------------------------------------------
Label analysis according to each atom:
               Mean             STD             Min             Max          Median           Range
      -1.079955e+04    4.657790e-01   -1.080093e+04   -1.079687e+04   -1.079960e+04    4.067901e+00
--------------------------

In [11]:
ds_md17.convert_units('nm', 'kj/mol')

Change the length unit from "Angstrom" to "nm"
Change the energy unit from "kcal mol-1" to "kJ mol-1"
---------------------------------------------------------------------------------------------------------
Label analysis according to graph:
               Mean             STD             Min             Max          Median           Range
      -4.066678e+05    1.753937e+01   -4.067200e+05   -4.065668e+05   -4.066696e+05    1.531809e+02
---------------------------------------------------------------------------------------------------------
Label analysis according to each atom:
               Mean             STD             Min             Max          Median           Range
      -4.518531e+04    1.948819e+00   -4.519111e+04   -4.517409e+04   -4.518551e+04    1.702010e+01
---------------------------------------------------------------------------------------------------------
Force norm analysis:
               Mean             STD             Max          Median
       1.631667e+

In [12]:
ds_md17.shuffle_dataset()

array([400641, 368279, 191028, ..., 472341, 432466, 489340], dtype=int32)

In [13]:
ds_md17.save_dataset('dataset_ethanol', 1024, 128, 1024, mode='atomwise')

              Scale           Shift        Mode
       1.948819e+00   -4.518531e+04    atomwise
---------------------------------------------------------------------------------------------------------
Number of Training, Validation and Test dataset: 1024, 128, 1024.
---------------------------------------------------------------------------------------------------------
Dataset file:
   Training dataset    (normalized):   dataset_ethanol_normed_trainset_1024.npz
   Validation dataset  (normalized):   dataset_ethanol_normed_validset_128.npz
   Test dataset            (origin):   dataset_ethanol_origin_testset_1024.npz


({'name': 'md17',
  'num_atoms': 9,
  'num_dataset': 1024,
  'data_index': array([400641, 368279, 191028, ..., 242788, 231230, 325078], dtype=int32),
  'normed_dataset': False,
  'length_unit': 'nm',
  'energy_unit': 'kj/mol',
  'Z': array([[6, 6, 8, 1, 1, 1, 1, 1, 1]], dtype=int32),
  'R': array([[[ 2.96331048e-02,  3.10908398e-03, -4.97013703e-02],
          [-6.41979426e-02,  1.03869125e-01, -1.51194762e-02],
          [ 3.57570164e-02, -9.63143930e-02,  5.86009920e-02],
          ...,
          [-7.29799271e-02,  1.24461845e-01,  9.15509686e-02],
          [-4.24662121e-02,  1.97813913e-01, -6.94589838e-02],
          [-1.15442881e-02, -1.77935094e-01,  5.08302562e-02]],
  
         [[-2.26275586e-02, -2.83641815e-02, -4.32372727e-02],
          [-4.31834012e-02,  1.21230870e-01, -2.99445912e-02],
          [ 6.38210699e-02, -8.52831453e-02,  6.08999692e-02],
          ...,
          [ 4.15716097e-02,  1.46736056e-01,  3.97364050e-02],
          [-4.70042713e-02,  1.75985053e-01, -